
export function getThemeStyles(theme) {
  const map = {
    light: {
      pageBg: '#ffffff',
      sectionAlt: '#f9fafb',
      cardBg: '#ffffff',
      cardBgAlt: '#fafafa',
      textPrimary: '#111827',
      textSecondary: '#374151',
      textMuted: '#6b7280',
      textFaint: '#9ca3af',
      border: '#e5e7eb',
      borderLight: '#f3f4f6',
      inputBg: '#ffffff',
      btnPrimaryBg: '#111827',
      btnPrimaryText: '#ffffff',
      btnOutlineBorder: '#d1d5db',
      btnOutlineText: '#374151',
      accent: '#23e5db',
      accentText: '#0f766e',
      headerBg: '#ffffff',
      headerBorder: '#e5e7eb',
      tagText: '#6b7280',
    },
    dark: {
      pageBg: '#0f1117',
      sectionAlt: '#13151f',
      cardBg: '#1e2130',
      cardBgAlt: '#252836',
      textPrimary: '#e8eaf0',
      textSecondary: '#c5c9d6',
      textMuted: '#8892a4',
      textFaint: '#6b7280',
      border: '#2e3347',
      borderLight: '#252836',
      inputBg: '#252836',
      btnPrimaryBg: '#e8eaf0',
      btnPrimaryText: '#0f1117',
      btnOutlineBorder: '#2e3347',
      btnOutlineText: '#c5c9d6',
      accent: '#23e5db',
      accentText: '#23e5db',
      headerBg: '#1a1d27',
      headerBorder: '#2e3347',
      tagText: '#8892a4',
    },
    ocean: {
      pageBg: '#e8f4fd',
      sectionAlt: '#daeaf8',
      cardBg: '#ffffff',
      cardBgAlt: '#f0f7ff',
      textPrimary: '#0a3d62',
      textSecondary: '#1a5276',
      textMuted: '#5d82a0',
      textFaint: '#7fa8c4',
      border: '#b3d4f0',
      borderLight: '#d4e9f7',
      inputBg: '#ffffff',
      btnPrimaryBg: '#0a3d62',
      btnPrimaryText: '#ffffff',
      btnOutlineBorder: '#b3d4f0',
      btnOutlineText: '#1a5276',
      accent: '#1a73e8',
      accentText: '#1a73e8',
      headerBg: '#ffffff',
      headerBorder: '#b3d4f0',
      tagText: '#5d82a0',
    },
    sunset: {
      pageBg: '#fff3e8',
      sectionAlt: '#fde8d0',
      cardBg: '#ffffff',
      cardBgAlt: '#fff8f2',
      textPrimary: '#6b2d0e',
      textSecondary: '#7c3c1a',
      textMuted: '#a06040',
      textFaint: '#b87c58',
      border: '#f0cba8',
      borderLight: '#fde8d0',
      inputBg: '#ffffff',
      btnPrimaryBg: '#6b2d0e',
      btnPrimaryText: '#ffffff',
      btnOutlineBorder: '#f0cba8',
      btnOutlineText: '#7c3c1a',
      accent: '#f97316',
      accentText: '#c2410c',
      headerBg: '#ffffff',
      headerBorder: '#f0cba8',
      tagText: '#a06040',
    },
  }
  return map[theme] || map.light
}
